# ansible
version: "3.8"

services:
  # ansible:
  #   image: alpine/ansible:latest
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   volumes:
  #     - /var/docker-conf/standalone/ansible/data:/app
  
  semaphore:
    ports:
      - 3000:3000
    # image: semaphoreui/semaphore:latest
    image: alpine/ansible-semaphore:latest
    user: semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: semaphore-mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: Administrator
      SEMAPHORE_ADMIN_EMAIL: admin@domain.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    volumes:
      - /var/docker-conf/standalone/ansible/semaphore:/etc/semaphore
      # - /var/docker-data/standalone/ansible:/var/lib/semaphore

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    container_name: semaphore-mysql
    hostname: semaphore-mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore

volumes:
  semaphore-mysql:
