version: "3.8"

services:
  httpd:
    image: httpd:latest
    container_name: httpd
    depends_on: 
      - packer
    volumes:
      - ../boot:/usr/local/apache2/htdocs
    ports:
      - 8082:80


  packer:
    image: hashicorp/packer:latest
    container_name: packer
    depends_on: 
      - httpd 
    working_dir: /workspace
    volumes:
      - ../scripts:/workspace/scripts
      - ../pkr:/workspace/pkr
      - ../../common.pkr.hcl:/workspace/pkr/common.pkr.hcl
      - ../../global.env.auto.pkr.hcl:/workspace/pkr/global.env.auto.pkr.hcl
      - ../boot:/workspace/boot
    environment:
      - PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins
    command: ["scripts/entrypoint.sh"]
    entrypoint: ["/bin/sh"]