# httpd-test

version: "3.8"

services:
  web:
    image: httpd:latest
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - /var/docker-data/standalone/httpd/:/usr/local/apache2/htdocs/
    networks:
      - public-net

networks:
  public-net:
    name: public
    external: true